# [START app_yaml]
runtime: nodejs8
service: visiondemo

#runtime: nodejs
#env: flex

# [START env]
env_variables:
  production: true
  PORT: 3000
  GCLOUD_STORAGE_BUCKET: leeboonstra-visionocr
  GCLOUD_PROJECT: gke-pipeline-savelee-192517
# [END env]
# [END app_yaml]